#AtCoder系コンテスト用Makefile
#その道の人から見たらおこられそう
CXX = clang++
VERSION = -std=c++14
IN = input.txt

A: probA.cpp
	$(CXX) $(VERSION) $<

B: probB.cpp
	$(CXX) $(VERSION) $<

C: probC.cpp
	$(CXX) $(VERSION) $<

D: probD.cpp
	$(CXX) $(VERSION) $<

E: probE.cpp
	$(CXX) $(VERSION) $<

F: probF.cpp
	$(CXX) $(VERSION) $<

G: probG.cpp
	$(CXX) $(VERSION) $<

H: probH.cpp
	$(CXX) $(VERSION) $<

I: probI.cpp
	$(CXX) $(VERSION) $<

J: probJ.cpp
	$(CXX) $(VERSION) $<

K: probK.cpp
	$(CXX) $(VERSION) $<

do: a.out
	./$< < $(IN)
